#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "$0")/.."
REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || { echo "gh cannot see this repo; run from a clone with gh logged in" >&2; exit 1; })
TOTAL_STAGES=8

banner "review-bot setup"

stage "Who the bot works for"
say "This repo is public, so the accounts and people it reviews are not written down in it."
say "They go in one Actions secret instead, and the bot reviews nothing without it."
ask POLICY_OWNER "Your GitHub login (the only one who may comment /review):"
ask POLICY_REPO_OWNERS "Accounts and orgs whose repos it may review, comma separated [$POLICY_OWNER]:"
[[ -z "$POLICY_REPO_OWNERS" ]] && POLICY_REPO_OWNERS="$POLICY_OWNER"
ask POLICY_AUTHORS "Logins whose PRs are reviewed without asking, comma separated [$POLICY_OWNER]:"
[[ -z "$POLICY_AUTHORS" ]] && POLICY_AUTHORS="$POLICY_OWNER"
write_env POLICY_OWNER "$POLICY_OWNER"
write_env POLICY_REPO_OWNERS "$POLICY_REPO_OWNERS"
write_env POLICY_AUTHORS "$POLICY_AUTHORS"
json_list() { printf '%s' "$1" | tr ',' '\n' | sed 's/^ *//; s/ *$//' | grep -v '^$' | jq -R . | jq -s -c .; }
REVIEWBOT_POLICY=$(jq -n -c --arg owner "$POLICY_OWNER" \
  --argjson repo_owners "$(json_list "$POLICY_REPO_OWNERS")" \
  --argjson authors "$(json_list "$POLICY_AUTHORS")" \
  '{owner: $owner, allowed_repo_owners: $repo_owners, allowed_authors: $authors}')
set_secret REVIEWBOT_POLICY "$REVIEWBOT_POLICY"
note "Change it later with: gh secret set REVIEWBOT_POLICY, then run the Deploy worker workflow."

stage "OpenRouter API key"
say "The reviewer calls OpenRouter with the openrouter/free router, so it costs nothing."
open_url "https://openrouter.ai/settings/keys"
step "Create key, name it review-bot, no credit limit needed. Copy it."
ask_secret OPENROUTER_API_KEY "Paste the OpenRouter key:"
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
set_secret OPENROUTER_API_KEY "$OPENROUTER_API_KEY"

stage "Cloudflare account and API token"
say "The webhook relay is a Cloudflare Worker on the free plan. CI deploys it with these two values."
open_url "https://dash.cloudflare.com/"
step "Open Workers & Pages. The Account ID is in the right sidebar (or in the URL after dash.cloudflare.com/)."
ask CLOUDFLARE_ACCOUNT_ID "Paste the Account ID:"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token, use the 'Edit Cloudflare Workers' template, keep the defaults, Continue, Create Token. Copy it."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
set_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

stage "Webhook secret"
say "GitHub signs every webhook with this. The Worker rejects anything that does not match."
WEBHOOK_SECRET=$(_existing WEBHOOK_SECRET || true)
if [[ -z "$WEBHOOK_SECRET" ]]; then
  WEBHOOK_SECRET=$(openssl rand -hex 32)
  say "Generated a new one."
else
  say "Reusing the one already in $ENV_FILE."
fi
write_env WEBHOOK_SECRET "$WEBHOOK_SECRET"
set_secret WEBHOOK_SECRET "$WEBHOOK_SECRET"
note "You will paste it into the GitHub App form in a later stage."
pause

stage "Dispatch token"
say "The Worker needs a token to start the review workflow in this repo. A fine-grained token"
say "scoped to this one repo is the smallest thing that works."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: review-bot-dispatch. Expiration: 1 year (custom). Repository access: Only select repositories, pick this repo."
step "Repository permissions: Contents, Read and write. Nothing else. Generate token, copy it."
warn "Put a calendar reminder a year out: when it expires the bot goes silent with 401s in the Worker."
ask_secret DISPATCH_TOKEN "Paste the token:"
set_secret DISPATCH_TOKEN "$DISPATCH_TOKEN"

stage "Deploy the Worker"
say "Running the deploy workflow on GitHub Actions so the Worker exists before the App points at it."
if gh workflow run deploy-worker.yml >/dev/null 2>&1; then
  sleep 5
  RUN_ID=$(gh run list --workflow=deploy-worker.yml --limit 1 --json databaseId -q '.[0].databaseId' 2>/dev/null || true)
  if [[ -n "$RUN_ID" ]]; then
    if gh run watch "$RUN_ID" --exit-status >/dev/null 2>&1; then
      say "Deploy succeeded."
    else
      warn "Deploy run $RUN_ID did not succeed; check it with: gh run view $RUN_ID --log"
    fi
    WEBHOOK_URL=$(gh run view "$RUN_ID" --log 2>/dev/null | grep -oE 'https://review-bot-relay\.[a-z0-9-]+\.workers\.dev' | head -n1 || true)
  fi
else
  warn "Could not start the workflow. It only exists once this branch is merged to master."
  SKIPPED+=("deploy the Worker: gh workflow run deploy-worker.yml")
fi
if [[ -n "${WEBHOOK_URL:-}" ]]; then
  say "Worker URL: $WEBHOOK_URL"
else
  step "Find the Worker URL in the deploy log or at Workers & Pages > review-bot-relay. It looks like https://review-bot-relay.<you>.workers.dev"
  ask WEBHOOK_URL "Paste the Worker URL:"
fi
write_env WEBHOOK_URL "$WEBHOOK_URL"

stage "GitHub App"
say "Now the App itself. Fill the form exactly like this:"
open_url "https://github.com/settings/apps/new"
step "GitHub App name: something unique, e.g. <you>-review-bot. Homepage URL: the URL of this repo."
step "Webhook: Active. Webhook URL: $WEBHOOK_URL"
step "Webhook secret: $WEBHOOK_SECRET"
step "Repository permissions: Contents Read-only; Issues Read and write; Pull requests Read and write. (Metadata is added automatically.)"
step "Subscribe to events: Issue comment, Pull request."
step "Where can this GitHub App be installed: Any account. An org you own counts as another account, so this is the only setting that lets the bot run on org repos."
note "allowed_repo_owners is what keeps it yours: the Worker drops webhooks from any other owner before they cost a run."
step "Create GitHub App. On the next page copy the App ID (top of the General tab)."
ask APP_ID "Paste the App ID:"
write_env APP_ID "$APP_ID"
set_var APP_ID "$APP_ID"
step "Scroll to Private keys, Generate a private key. A .pem file downloads."
ask APP_PRIVATE_KEY_PATH "Path to the downloaded .pem file:"
APP_PRIVATE_KEY_PATH="${APP_PRIVATE_KEY_PATH/#\~/$HOME}"
if [[ -f "$APP_PRIVATE_KEY_PATH" ]]; then
  write_env APP_PRIVATE_KEY_PATH "$APP_PRIVATE_KEY_PATH"
  set_secret APP_PRIVATE_KEY "$(cat "$APP_PRIVATE_KEY_PATH")"
else
  warn "No file at $APP_PRIVATE_KEY_PATH"
  SKIPPED+=("GitHub secret APP_PRIVATE_KEY (gh secret set APP_PRIVATE_KEY < the .pem file)")
fi

stage "Install the App"
say "Install it on every repo whose PRs it should review. Installing on this repo too means it reviews its own PRs."
say "Install it once per account: your own, then each org you own."
ask APP_SLUG "App slug (the name you gave it, lowercased with dashes):"
open_url "https://github.com/apps/$APP_SLUG/installations/new"
step "Pick the account, then Only select repositories, choose the repos, Install. Repeat for each org."
warn "Every account you install on must be in allowed_repo_owners, and the Worker only picks up a changed list when the Deploy worker workflow runs."
pause "Installed?"
say "Test: open a PR as yourself on one of those repos. The Worker answers GitHub with 'queued',"
say "a Review run appears under Actions here, and a review lands on the PR a minute or two later."
say "Add or remove authors and owners with: gh secret set REVIEWBOT_POLICY, then run the Deploy worker workflow."
say "Comment /review on any PR to review it regardless of author."

finish
